image: node:latest

stages:
    - build
    - test
    - staging
    - production

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  only:
    changes:
      - package.json

testing_testing:
  stage: test
  image: alekzonder/puppeteer:1.5.0-0
  script:
    # - npm test
    - npm version

staging:
    type: deploy
    stage: staging
    image: ruby:latest
    before_script:
      - apt-get update -qy
      - apt-get install -y ruby-dev
      - gem install dpl
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY_STAGING
    only:
        - develop

production:
    type: deploy
    stage: production
    image: ruby:latest
    before_script:
      - apt-get update -qy
      - apt-get install -y ruby-dev
      - gem install dpl
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    only:
        - master