export const GET_PASSENGERS = 'GET_PASSENGERS';
export const CREATE_PASSENGER = 'CREATE_PASSENGER';
export const GET_PASSENGER = 'GET_PASSENGER';
export const UPDATE_PASSENGER = 'UPDATE_PASSENGER';
export const DELETE_PASSENGER = "DELETE_PASSENGER";